# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='work_summary',
            field=models.TextField(blank=True, help_text='Tasks performed / work done (visible to other employers)', null=True),
        ),
    ]
