# Generated by Django 5.2.11 on 2026-02-12 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('paystack_event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_in_kobo', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='product_jobapplication_job_listing_employee_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job_listing', 'employee')},
        ),
        migrations.AddField(
            model_name='paystackdeposit',
            name='escrow_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_deposits', to='product.escrowcontract'),
        ),
    ]
