# Generated by Django 5.2.11 on 2026-02-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_joblisting_work_summary'),
        ('product', '0004_paystackdeposit_and_more'),
    ]

    operations = [
    ]
