# Generated by Django 5.2.11 on 2026-02-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_jobmessage'),
        ('product', '0005_merge_20260212_0213'),
    ]

    operations = [
    ]
